{% set org = "tdegeus" %}
{% set name = "GMatElastoPlasticQPot" %}
{% set version = "0.15.2" %}

package:
  name: python-{{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ org }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: ddb1cb295f60fa9698565a0d6eb9b45731cd6ab1cf49bf6a489fd2fa433e7e35

build:
  number: 0
  script_env: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - pip
    - setuptools_scm
    - pyxtensor
    - qpot
    - gmattensor
  run:
    - python
    - python-qpot

test:
  imports:
    - {{ name }}
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/{{ org }}/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Elasto-plastic model based on a manifold of quadratic potentials (Python wrapper).
  description: Elasto-plastic model based on a manifold of quadratic potentials (Python wrapper).
  doc_url: https://{{ org }}.github.io/{{ name }}
  dev_url: https://github.com/{{ org }}/{{ name }}

extra:
  recipe-maintainers:
    - tdegeus
