{% set name = "python-gmatelastoplasticqpot" %}
{% set version = "0.6.0" %}
{% set sha256 = "3205c183838ef715222822bbfc0342adf55b63d4788600b625fc761ca28578eb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tdegeus/GMatElastoPlasticQPot/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - pip
    - pyxtensor
    - qpot
  run:
    - python

test:
  imports:
    - GMatElastoPlasticQPot

about:
  home: https://github.com/tdegeus/GMatElastoPlasticQPot
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Elasto-plastic model based on a manifold of quadratic potentials (Python wrapper).
  description: Elasto-plastic model based on a manifold of quadratic potentials (Python wrapper).
  doc_url: https://github.com/tdegeus/GMatElastoPlasticQPot
  dev_url: https://github.com/tdegeus/GMatElastoPlasticQPot

extra:
  recipe-maintainers:
    - tdegeus
